### Create a new Course
POST http://localhost:8080/api/courses
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "Advanced Java Architectures",
  "description": "Learning how to build enterprise Spring Boot apps."
}

### Get all Courses
GET http://localhost:8080/api/courses
Authorization: Bearer {{access_token}}