spring:
  application:
    name: nexuslearn-api

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/classroom_db
    username: admin
    password: rootpassword
    driver-class-name: org.postgresql.Driver

  # JPA & Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Flyway Migration Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

  # Docker Compose Auto-Start
  docker:
    compose:
      file: ./compose.yaml
      lifecycle-management: start-only

server:
  port: 8080

app:
  jwt:
    # Local development jwt
    secret: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
    # Access token: 15 minutes (900000 ms)
    expiration-ms: 900000
    # Refresh token: 7 days (604800000 ms)
    refresh-expiration-ms: 604800000